apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-frontend
  namespace: tweet-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-frontend
  template:
    metadata:
      labels:
        app: tweet-frontend
    spec:
      containers:
      - name: tweet-frontend
        image: tweet-frontend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          value: http://tweet-api:8000
        - name: FLASK_APP
          value: app.py
        - name: FLASK_ENV
          value: production
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tweet-frontend
  namespace: tweet-analytics
spec:
  selector:
    app: tweet-frontend
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tweet-frontend-ingress
  namespace: tweet-analytics
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tweet-analytics.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tweet-frontend
            port:
              number: 80
