apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-processor
  namespace: tweet-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-processor
  template:
    metadata:
      labels:
        app: tweet-processor
    spec:
      containers:
      - name: tweet-processor
        image: tweet-processor:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: ES_HOST
          value: elasticsearch:9200
        - name: CONTINUOUS_MODE
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /app/config.ini
          subPath: config.ini
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: config
        configMap:
          name: tweet-processor-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tweet-processor-config
  namespace: tweet-analytics
data:
  config.ini: |
    [kafka]
    bootstrap_servers = kafka:9092
    input_topic = raw-tweets
    output_topic = processed-tweets
    group_id = tweet-processor

    [elasticsearch]
    hosts = elasticsearch:9200
    index = tweets
    bulk_size = 1000

    [processing]
    window_size = 60
    slide_interval = 10
    min_hashtag_count = 2
    language_filter = en
